// Generated by diesel_ext



#![allow(unused)]
#![allow(clippy::all)]



use diesel::prelude::*;
use crate::schema::auth;
use serde_derive::{Serialize,Deserialize};





#[derive(Queryable, Debug,Serialize, Deserialize)]
pub struct Auth {
    pub id: i32,
    pub name: String,
    pub password: String,
    pub numero: Option<String>,
    pub serie: String,
    pub email: String,
    pub id_firebase: String,
    pub token_firebase: Option<String>,
    pub created_on: Option<String>,
    pub last_login: Option<String>,
}

#[derive(Insertable, Debug, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = auth)]
pub struct NewAuth {
    pub name: String,
    pub password: String,
    pub numero: Option<String>,
    pub serie: String,
    pub email: String,
    pub id_firebase: String,
    pub token_firebase: Option<String>,
    pub created_on: Option<String>,
    pub last_login: Option<String>,
}


#[derive(Insertable, Debug, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = auth)]
pub struct AuthResponse {
    pub id: i32,
    pub name: String,
    pub numero: Option<String>,
    pub serie: String,
    pub email: String,
    pub id_firebase: String,
    pub token_firebase: Option<String>,

}

#[derive(Queryable, Debug,Serialize, Deserialize)]
pub struct AuthLogin {
    pub password: String,
    pub email: String,

}

#[derive(Debug,Serialize, Deserialize)]
pub struct AuthRes{
    pub id: i32,
    pub email: String,
    pub token: String,

}