[package]
name = "migre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html




[dependencies]
jcore = { path = "../jcore", features =["tokio","derives"] }




[features]
jcore = ["jcore/tokio","jcore/derives"]





